(function(n,w,p){if("object"===typeof p&&"string"!==typeof p.nodeName)w(n,p);else{var u=function(d){for(var l in d)d.hasOwnProperty(l)&&(d[l]=u(d[l]));return Object.freeze(d)};p={};w(n,p);for(var q in p)!p.hasOwnProperty(q)||null!=Object.getOwnPropertyDescriptor(n,q)&&null!=Object.getOwnPropertyDescriptor(n[q],"1.2.6-iab634")||(null==Object.getOwnPropertyDescriptor(n,q)&&Object.defineProperty(n,q,{value:{}}),Object.defineProperty(n[q],"1.2.6-iab634",{get:function(){return u(p[q])},enumerable:!0}))}})("undefined"===
typeof global?this:global,function(n,w){function p(a,c){return a&&(a[c]||(a[c]={}))}function u(a,c){"undefined"!==typeof jasmine&&jasmine?a():"undefined"!==typeof console&&console&&console.error&&c()}function q(a,c){return c.reduce(function(a,c){return a&&a[c]},a)}var d=d||{};d.scope={};d.inherits=function(a,c){function b(){}b.prototype=c.prototype;a.superClass_=c.prototype;a.prototype=new b;a.prototype.constructor=a;for(var d in c)if("prototype"!=d)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(c,
d);e&&Object.defineProperty(a,d,e)}else a[d]=c[d]};d.ASSUME_ES5=!1;d.ASSUME_NO_NATIVE_MAP=!1;d.ASSUME_NO_NATIVE_SET=!1;d.defineProperty=d.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};d.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};d.global=d.getGlobal(this);d.SYMBOL_PREFIX="jscomp_symbol_";d.initSymbol=function(){d.initSymbol=
function(){};d.global.Symbol||(d.global.Symbol=d.Symbol)};d.symbolCounter_=0;d.Symbol=function(a){return d.SYMBOL_PREFIX+(a||"")+d.symbolCounter_++};d.initSymbolIterator=function(){d.initSymbol();var a=d.global.Symbol.iterator;a||(a=d.global.Symbol.iterator=d.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&d.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return d.arrayIterator(this)}});d.initSymbolIterator=function(){}};d.arrayIterator=function(a){var c=
0;return d.iteratorPrototype(function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}})};d.iteratorPrototype=function(a){d.initSymbolIterator();a={next:a};a[d.global.Symbol.iterator]=function(){return this};return a};d.makeIterator=function(a){d.initSymbolIterator();var c=a[Symbol.iterator];return c?c.call(a):d.arrayIterator(a)};d.arrayFromIterator=function(a){for(var c,b=[];!(c=a.next()).done;)b.push(c.value);return b};d.arrayFromIterable=function(a){return a instanceof Array?a:d.arrayFromIterator(d.makeIterator(a))};
var l={assertTruthyString:function(a,c){if(!c)throw Error("Value for "+a+" is undefined, null or blank.");if("string"!==typeof c&&!(c instanceof String))throw Error("Value for "+a+" is not a string.");if(""===c.trim())throw Error("Value for "+a+" is empty string.");},assertNotNullObject:function(a,c){if(null==c)throw Error("Value for "+a+" is undefined or null");},assertNumber:function(a,c){if(null==c)throw Error(a+" must not be null or undefined.");if("number"!==typeof c||isNaN(c))throw Error("Value for "+
a+" is not a number");},assertNumberBetween:function(a,c,b,d){(0,l.assertNumber)(a,c);if(c<b||c>d)throw Error("Value for "+a+" is outside the range ["+b+","+d+"]");},assertFunction:function(a,c){if(!c)throw Error(a+" must not be truthy.");},assertPositiveNumber:function(a,c){(0,l.assertNumber)(a,c);if(0>c)throw Error(a+" must be a positive number.");}};var t=function(a){return/\d+\.\d+\.\d+(-.*)?/.test(a)};var x=function(a,c){a=a.split("-")[0].split(".");c=c.split("-")[0].split(".");for(var b=0;3>
b;b++){var d=parseInt(a[b],10),e=parseInt(c[b],10);if(d>e)break;else if(d<e)return!1}return!0};var v=function(a,c){return(0,t)(a)&&(0,x)(a,"1.0.3")?c:JSON.stringify(c)};var A=function(a,c){return(0,t)(a)&&(0,x)(a,"1.0.3")?c?c:[]:c&&"string"===typeof c?JSON.parse(c):[]};var r=function(a,c,b,d){this.guid=a;this.method=c;this.version=b;this.args=d};r.isValidSerializedMessage=function(a){return!!a&&void 0!==a.omid_message_guid&&void 0!==a.omid_message_method&&void 0!==a.omid_message_version&&"string"===
typeof a.omid_message_guid&&"string"===typeof a.omid_message_method&&"string"===typeof a.omid_message_version&&(void 0===a.omid_message_args||void 0!==a.omid_message_args)};r.deserialize=function(a){return new r(a.omid_message_guid,a.omid_message_method,a.omid_message_version,a.omid_message_args)};r.prototype.serialize=function(){var a={};a=(a.omid_message_guid=this.guid,a.omid_message_method=this.method,a.omid_message_version=this.version,a);void 0!==this.args&&(a.omid_message_args=this.args);return a};
var m=function(a){this.to=a;this.communicationType_="NONE"};m.prototype.sendMessage=function(a,c){};m.prototype.handleMessage=function(a,c){if(this.onMessage)this.onMessage(a,c)};m.prototype.generateGuid=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var c=16*Math.random()|0;return a="y"===a?(c&3|8).toString(16):c.toString(16)})};m.prototype.serialize=function(a){return JSON.stringify(a)};m.prototype.deserialize=function(a){return JSON.parse(a)};m.prototype.isDirectCommunication=
function(){return"DIRECT"===this.communicationType_};var g={OMID_PRESENT_FRAME_NAME:"omid_v1_present",isOmidPresent:function(a){try{return a.frames?!!a.frames[g.OMID_PRESENT_FRAME_NAME]:!1}catch(c){return!1}},declareOmidPresence:function(a){a.frames&&a.document&&(g.OMID_PRESENT_FRAME_NAME in a.frames||(null==a.document.body&&g.isMutationObserverAvailable_(a)?g.registerMutationObserver_(a):a.document.body?g.appendPresenceIframe_(a):a.document.write('<iframe style="display:none" '+('id="'+g.OMID_PRESENT_FRAME_NAME+
'"')+(' name="'+g.OMID_PRESENT_FRAME_NAME+'">')+"</iframe>")))},appendPresenceIframe_:function(a){var c=a.document.createElement("iframe");c.id=g.OMID_PRESENT_FRAME_NAME;c.name=g.OMID_PRESENT_FRAME_NAME;c.style.display="none";a.document.body.appendChild(c)},isMutationObserverAvailable_:function(a){return"MutationObserver"in a},registerMutationObserver_:function(a){var c=new MutationObserver(function(b){b.forEach(function(b){"BODY"===b.addedNodes[0].nodeName&&(g.appendPresenceIframe_(a),c.disconnect())})});
c.observe(a.document.documentElement,{childList:!0})}},b=function(a){m.call(this,a);this.communicationType_="DIRECT";this.handleExportedMessage=b.prototype.handleExportedMessage.bind(this)};d.inherits(b,m);b.prototype.sendMessage=function(a,c){c=void 0===c?this.to:c;if(!c)throw Error("Message destination must be defined at construction time or when sending the message.");c.handleExportedMessage(a.serialize(),this)};b.prototype.handleExportedMessage=function(a,c){r.isValidSerializedMessage(a)&&this.handleMessage(r.deserialize(a),
c)};var h={error:function(a){for(var c=[],b=0;b<arguments.length;++b)c[b-0]=arguments[b];u(function(){throw new (Function.prototype.bind.apply(Error,[null].concat(["Could not complete the test successfully - "],d.arrayFromIterable(c))));},function(){return console.error.apply(console,[].concat(d.arrayFromIterable(c)))})},debug:function(a){for(var c=[],b=0;b<arguments.length;++b)c[b-0]=arguments[b];u(function(){},function(){return console.error.apply(console,[].concat(d.arrayFromIterable(c)))})}},
f=eval("this");var e=function(){if("undefined"!==typeof n&&n)return n;if("undefined"!==typeof global&&global)return global;if("undefined"!==typeof window&&window)return window;if("undefined"!==typeof f&&f)return f;throw Error("Could not determine global object context.");}();var z=function(a,c){c=void 0===c?e:c;m.call(this,c);var b=this;this.communicationType_="POST_MESSAGE";a.addEventListener("message",function(a){if("object"===typeof a.data){var c=a.data;r.isValidSerializedMessage(c)&&(c=r.deserialize(c),
a.source&&b.handleMessage(c,a.source))}})};d.inherits(z,m);z.isCompatibleContext=function(a){return!!(a&&a.addEventListener&&a.postMessage)};z.prototype.sendMessage=function(a,c){c=void 0===c?this.to:c;if(!c)throw Error("Message destination must be defined at construction time or when sending the message.");c.postMessage(a.serialize(),"*")};var y=function(a){"undefined"===typeof a&&"undefined"!==typeof window&&window&&(a=window);if("undefined"===typeof a||!a||"undefined"===typeof a.top||!a.top)return e;
if(a===a.top)return a;try{return"undefined"===typeof a.top.location.hostname?a:a.top}catch(c){return a}};var B=function(a,c,d){d=void 0===d?g.isOmidPresent:d;return(c=q(a,c))?new b(c):a.top&&d(a.top)?new z(a,a.top):null};var k=function(a){if(this.communication=void 0===a?(0,B)((0,y)(),["omid","v1_VerificationServiceCommunication"]):a)this.communication.onMessage=this.handleMessage_.bind(this);else if(a=(a=e.omid3p)&&"function"===typeof a.registerSessionObserver&&"function"===typeof a.addEventListener?
a:null)this.omid3p=a;this.remoteIntervals_=this.remoteTimeouts_=0;this.callbackMap_={};this.imgCache_=[]};k.prototype.isSupported=function(){return!!this.communication};k.prototype.registerSessionObserver=function(a,c){(0,l.assertFunction)("functionToExecute",a);this.omid3p?this.omid3p.registerSessionObserver(a,c):this.sendMessage_("addSessionListener",a,c)};k.prototype.addEventListener=function(a,c){(0,l.assertTruthyString)("eventType",a);(0,l.assertFunction)("functionToExecute",c);this.omid3p?this.omid3p.addEventListener(a,
c):this.sendMessage_("addEventListener",c,a)};k.prototype.sendUrl=function(a,c,b){(0,l.assertTruthyString)("url",a);e.document&&e.document.createElement?this.sendUrlWithImg_(a,c,b):this.sendMessage_("sendUrl",function(a){a&&c?c():!a&&b&&b()},a)};k.prototype.sendUrlWithImg_=function(a,c,b){var d=this,h=e.document.createElement("img");this.imgCache_.push(h);var f=function(a){var c=d.imgCache_.indexOf(h);0<=c&&d.imgCache_.splice(c,1);a&&a()};h.addEventListener("load",f.bind(this,c));h.addEventListener("error",
f.bind(this,b));h.src=a};k.prototype.injectJavaScriptResource=function(a,c,b){var d=this;(0,l.assertTruthyString)("url",a);e.document?this.injectJavascriptResourceUrlInDom_(a,c,b):this.sendMessage_("injectJavaScriptResource",function(e,f){e?(d.evaluateJavaScript_(f,a),c()):(h.error("Service failed to load JavaScript resource."),b())},a)};k.prototype.injectJavascriptResourceUrlInDom_=function(a,c,b){var d=e.document,h=d.body;d=d.createElement("script");d.onload=c;d.onerror=b;d.src=a;d.type="application/javascript";
h.appendChild(d)};k.prototype.evaluateJavaScript_=function(a,c){try{eval(a)}catch(C){h.error('Error evaluating the JavaScript resource from "'+c+'".')}};k.prototype.setTimeout=function(a,c){(0,l.assertFunction)("functionToExecute",a);(0,l.assertPositiveNumber)("timeInMillis",c);if(this.hasTimeoutMethods_())return e.setTimeout(a,c);var b=this.remoteTimeouts_++;this.sendMessage_("setTimeout",a,b,c);return b};k.prototype.clearTimeout=function(a){(0,l.assertPositiveNumber)("timeoutId",a);this.hasTimeoutMethods_()?
e.clearTimeout(a):this.sendOneWayMessage_("clearTimeout",a)};k.prototype.setInterval=function(a,c){(0,l.assertFunction)("functionToExecute",a);(0,l.assertPositiveNumber)("timeInMillis",c);if(this.hasIntervalMethods_())return e.setInterval(a,c);var b=this.remoteIntervals_++;this.sendMessage_("setInterval",a,b,c);return b};k.prototype.clearInterval=function(a){(0,l.assertPositiveNumber)("intervalId",a);this.hasIntervalMethods_()?e.clearInterval(a):this.sendOneWayMessage_("clearInterval",a)};k.prototype.hasTimeoutMethods_=
function(){return"function"===typeof e.setTimeout&&"function"===typeof e.clearTimeout};k.prototype.hasIntervalMethods_=function(){return"function"===typeof e.setInterval&&"function"===typeof e.clearInterval};k.prototype.handleMessage_=function(a,c){c=a.method;var b=a.guid;a=a.args;if("response"===c&&this.callbackMap_[b]){var d=(0,A)("1.2.6-iab634",a);this.callbackMap_[b].apply(this,d)}"error"===c&&window.console&&h.error(a)};k.prototype.sendOneWayMessage_=function(a,c){for(var b=[],e=1;e<arguments.length;++e)b[e-
1]=arguments[e];this.sendMessage_.apply(this,[].concat([a,null],d.arrayFromIterable(b)))};k.prototype.sendMessage_=function(a,c,b){for(var d=[],e=2;e<arguments.length;++e)d[e-2]=arguments[e];this.communication&&(e=this.communication.generateGuid(),c&&(this.callbackMap_[e]=c),d=new r(e,"VerificationService."+a,"1.2.6-iab634",(0,v)("1.2.6-iab634",d)),this.communication.sendMessage(d))};(0,function(a,c,b){if(b=void 0===b?"undefined"===typeof w?null:w:b)a=a.split("."),a.slice(0,a.length-1).reduce(p,b)[a[a.length-
1]]=c})("OmidVerificationClient",k)},"undefined"===typeof exports?void 0:exports);
(function(){function n(){var b={location:{protocol:"https:"}};b.parent=b;b.top=b;b.document={getElementById:function(){},createElement:function(){},body:{insertBefore:function(){}},querySelectorAll:function(){return[]}};return b}function w(b,d){var h=g.getReportUrl(g.ErrorTypes.LoadTagError,"failedToLoadDVM",!0),e=b&&(b.contentDocument||b.contentWindow&&b.contentWindow.document||frames&&frames[b.name]&&frames[b.name].document);d='<html><head><script type="text/javascript">('+function(){window.$dv=
window.parent.$dv;window.$dv.isFrameSupported=!0;window.$frmId=Math.random().toString(36)+Math.random().toString(36);window.dv_flow=2}.toString()+')();\x3c/script></head><body><script type="text/javascript">('+function(b,d){if(b){var e=document.createElement("script");e.src=b;e.onerror=function(){(new Image(1,1)).src=d};document.body.appendChild(e)}}.toString()+')("'+d+'", "'+h+'");\x3c/script></body></html>';e?(e.open(),e.write(d),e.close()):(e=encodeURIComponent(d.replace(/'/g,"\\'").replace(/\n|\r\n|\r/g,
"")),b.src='javascript: (function(){document.open();document.domain="'+window.document.domain+"\";document.write('"+e+"');})()")}function p(b){var d=Math.floor(1E12*(Math.random()+"")),f=document.createElement("iframe");f.name=f.id="iframe_"+d;f.setAttribute("data-dv-frm",d);f.width="0";f.height="0";f.style.display="none";f.src="about:blank";document.currentScript?document.currentScript.parentNode.insertBefore(f,document.currentScript):document.body?document.body.insertBefore(f,document.body.firstChild):
(d=document.getElementsByTagName("head")[0],d.insertBefore(f,d.firstChild));w(f,b)}function u(b,h){$frmId=Math.random().toString(36)+Math.random().toString(36);b.injectJavaScriptResource(h,function(){},function(){var b=g.getReportUrl(g.ErrorTypes.OmidLoadTagError,"",!0);d(b)})}function q(b){try{(new Image(1,1)).src=b}catch(h){}}function d(b,d,f){d=d||function(){};f=f||function(){};if(t){if("object"===typeof omidNative&&"function"===typeof omidNative.sendUrl)return omidNative.sendUrl(b,d,f)}else{var e=
new Image(1,1);e.onerror=f;e.onload=d;e.src=b}}function l(b,d,f){b||(b={message:"error undefined"});b=["https://tps.doubleverify.com/visit.jpg?ctx=818052&cmp=1619415&dvtagver=6.1.src&dvp_isLostImp=",f,"&dvp_jsErrMsg=",b.message,"&napr=",b.message,"&cerrt=",d,"&tgjsver=361"].join("");t&&(b+="&dvp_idle=1");v.isSupported()&&(b+="&dvp_iomd=1");b=encodeURI(b);v.isSupported()?v.report(b):q(b)}dv_flow=2;var t=!1;"undefined"===typeof window&&(t=!0);var x=function(){var b;return{getMeasurementsScriptUrl:function(d){if(!b){var f=
[{src:"dv-measurements"}];b=f&&f[0]}return b&&[d,"//cdn.doubleverify.com/",b.src,"361.js"].join("")}}}(),v={omidObject:null,isOmidSupported:null,report:d,isSupported:function(){if(null!==this.isOmidSupported&&void 0!==this.isOmidSupported)return this.isOmidSupported;try{this.omidObject||(this.omidObject=new OmidVerificationClient["1.2.6-iab634"]),this.isOmidSupported=this.omidObject.isSupported()}catch(h){if(this.isOmidSupported=!1,g){var b=g.getReportUrl(g.ErrorTypes.OmidUnexpectedError,"isSupported__"+
h.message,!1);this.report(b)}}return this.isOmidSupported},getVendorKey:function(){if(!t&&m){var b=(b=m.getQueryStringParams())&&b.vendor_key;window.$dv.omidVendorKeyExtracted=Number(!!b)}return b||"doubleverify.com-omid"},execute:function(){var b=this,h=this.omidObject;"undefined"!=typeof $dv?($dv.dvtpScriptVersion="361",$dv.tagsCounter=$dv.tagsCounter||0,$dv.tagsCounter++,$dv.omidJsClient=h):$dv={omidJsClient:h,tags:{},tagsCounter:1};$dv.isDomlessEnvironment=t;var f=this.getVendorKey();$dv.omidVendorKey=
f;t&&(window=n());h.registerSessionObserver(function(e){try{switch(e.type){case "sessionStart":$dv.omidSessionData=e;$dv.omidAccessMode=e&&e.data&&e.data.context&&e.data.context.accessMode;try{$dv.omidSessionStartTime=Date.now?Date.now():(new Date).getTime()}catch(k){var f=g.getReportUrl(g.ErrorTypes.OmidUnexpectedError,"Date.now__"+k.message,!1);d(f)}var y=x.getMeasurementsScriptUrl("https:");if($dv.isDomlessEnvironment){if(u(h,y),"object"===typeof omidNative){f=g.getReportUrl(g.ErrorTypes.OmidNativeCollectData,
"InjectJavascriptTracker",!1);d(f+"&dvp_ifdvtp=1");var l="https://cdn.doubleverify.com/dvprt.js?v="+Math.random()*Date.now();"function"===typeof omidNative.injectJavascriptResource?omidNative.injectJavascriptResource(l):"function"===typeof omidNative.downloadJavaScriptResource&&omidNative.downloadJavaScriptResource(l)}}else try{p(y)}catch(k){f=g.getReportUrl(g.ErrorTypes.OmidUnexpectedError,"injectScriptSteps__"+k.message,!1),d(f),u(h,y)}break;case "sessionError":f=g.getReportUrl(g.ErrorTypes.OmidSessionError,
e.data&&e.data.message||"",!0),b.report(f)}}catch(k){e=g.getReportUrl(g.ErrorTypes.OmidUnexpectedLostImpError,"omidCallback__"+k.message,!0),d(e)}},f)}},A={execute:function(){try{window.$dv=window.$dv||{tags:{}};window.$dv.dvtpScriptVersion="361";var b=document.currentScript&&0==document.currentScript.src.indexOf("http:")?"http:":"https:";var d=x.getMeasurementsScriptUrl(b);p(d)}catch(f){g.report(g.ErrorTypes.InjectTagError,f.message,!0)}}},r="";try{r=window&&window.document&&window.document.currentScript&&
window.document.currentScript.src}catch(b){}try{var m=function(b){function d(b){var d={};b.split("&").forEach(function(b){b=b.trim().split("=");2===b.length&&(d[b[0].trim()]=b[1].trim())});return d}function f(b){var d={};["cmp","ctx","sid","plc"].forEach(function(e){b.hasOwnProperty(e)&&(d["dvp_"+e]=b[e])});return d}var e={},g={};(function(b){if(b){var h="";b=b.trim().split("?");2===b.length&&(h=b[1]);h&&(e=d(h),g=f(e))}})(b);return{toQueryString:function(b){var d="",e;for(e in b)b.hasOwnProperty(e)&&
(d&&(d+="&"),d=[d,e,"=",b[e]].join(""));return d},getQueryStringParams:function(){return e},getQueryStringClientParams:function(){return g}}}(r);var g=function(){function b(b,f,g){f=(f=f&&f&&f.trim().replace(/(\t|\n|\r|\|)/g,""))&&encodeURIComponent(f)||"";f=d.replace(/__ERR_MSG_PLACEHOLDR__/g,[b.message,f].join("__"));f=f.replace(/__CLIENT_ERROR_TYPE_PLACEHOLDR__/g,b.id);g&&(f+="&dvp_isLostImp=1");v.isSupported()&&(f+="&dvp_iomd=1");return f}var d="",f={ctx:818052,cmp:1619415,dvtagver:"6.1.src",
tgjsver:"361",dvp_jsErrMsg:"__ERR_MSG_PLACEHOLDR__",napr:"__ERR_MSG_PLACEHOLDR__",cerrt:"__CLIENT_ERROR_TYPE_PLACEHOLDR__"};t&&(f.dvp_idle=1);d=["https://tps.doubleverify.com/visit.jpg?",[m.toQueryString(f),m.toQueryString(m.getQueryStringClientParams())].join("&")].join("");return{ErrorTypes:{OmidNativeCollectData:{id:512,message:"OmidNativeCollectData"},InjectTagError:{id:1,message:"InjectTagError"},LoadTagError:{id:2,message:"LoadTagError"},UnexpectedLostImpError:{id:4,message:"UnexpectedLostImpError"},
OmidSessionError:{id:8,message:"OmidSessionError"},OmidUnexpectedLostImpError:{id:16,message:"OmidUnexpectedLostImpError"},OmidLoadTagError:{id:32,message:"OmidLoadTagError"},OmidInjectTagError:{id:64,message:"OmidInjectTagError "},UnexpectedError:{id:128,message:"UnexpectedError"},OmidUnexpectedError:{id:256,message:"OmidUnexpectedError"}},report:function(d,f,g){q(b(d,f,g))},getReportUrl:b}}()}catch(b){l(b,128,0)}try{(v.isSupported()?v:A).execute()}catch(b){g?g.report(g.ErrorTypes.UnexpectedLostImpError,
b.message,!0):l(b,4,1)}})();
